name: DevKit Build

on:
    workflow_dispatch:
    pull_request:

jobs:
  build:
    runs-on: ubuntu-slim
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Make build script executable
        run: chmod +x build/build.sh
      
      - name: Execute build script
        run: ./build/build.sh
        working-directory: .
      
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: pos-system-api-devkit-${{ steps.date.outputs.date }}
          path: build/pos-system-api-devkit-package/
          if-no-files-found: error
